# SITE CONFIGURATION
baseurl:  # the subpath of your site, e.g. /blog/
url: "http://cdohub.com" # the base hostname & protocol for your site
timezone: "Europe/Berlin"

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: "Chief Data Officer Business School"
  avatar: CDO-Elephant3.png
  gravatar: # Email MD5 hash
  description: "The place to refine your Chief Data Officer skills, to learn how to create data-driven business value and to exchange with Chief Data Officers (CDO)." # used by search engines

  # Header and footer text
  header_text: <h1 class="title">CDO Business School Blog</h1>
     <i>"The place for CDOs to read, learn and discuss."</i>
  header_text_feature_image: img/header/banner-786084.jpg
  footer_text: © 2016 Miriam & Markus Schmidberger founders of the Chief Data Officer Business School<br><a href="/contact/">Contact</a> - <a href="/imprint/">Imprint</a>

  # Icons
  rss: true
  email_address: "info@cdohub.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github:
  google_plus:
  instagram:
  linkedin:
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: "CDOhub"
  wordpress:
  youtube:

  # Scripts
  google_analytics: "UA-73696258-1"
  disqus_shortname: "cdohub"
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"
  
  # Post navigation
  post_navigation: true

# PAGINATION
gems: [jekyll-paginate]
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
